EXEC = coati_test
TEST ?= bc

OBJECTS = main_$(TEST)_alpaca.o

DEPS = libmspbuiltins:gcc libio:gcc \
       libcapybara:gcc libmspware:gcc \
       libfxl:gcc libmsp:gcc libcoatigcc:gcc \
       libmspmath:gcc

#libmspmath:gcc

include tools/maker/Makefile


